In [98]:
import os, glob

print("CloudStorage contents:")
print(os.listdir(os.path.expanduser("~/Library/CloudStorage")))

print("\nPossible Box roots:")
print(glob.glob(os.path.expanduser("~/Library/CloudStorage/Box*")))

import os
import pandas as pd

BOX_ROOT = os.path.expanduser("~/Library/CloudStorage/Box-Box")

CloudStorage contents:
['.DS_Store', 'Box-Box']

Possible Box roots:
['/Users/aprillin/Library/CloudStorage/Box-Box']

In [99]:
import numpy as np
import pandas as pd
import Levenshtein 
import matplotlib.pyplot as plt
import seaborn as sns
import os
BOX_ROOT = os.path.expanduser("~/Library/CloudStorage/Box-Box")
DATA_PATH=os.path.join(
    BOX_ROOT,
    "WHT Datasets",
    "00_raw",
    "RealWorldHAR",
    "realworld2016_dataset",
    "proband14",
    "data")

In [100]:
# --- Gyroscope waist ---
gyro_motion_waist_path = os.path.join(DATA_PATH, "Gyroscope_walking_waist.csv")
gyro_motion_waist = pd.read_csv(gyro_motion_waist_path)
gyro_suffix = os.path.basename(gyro_motion_waist_path).replace(".csv","").split("_")[-1]
gyro_motion_waist.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_waist.columns
]

# --- Accelerometer waist ---
acc_motion_waist_path = os.path.join(DATA_PATH, "acc_walking_waist.csv")
acc_motion_waist = pd.read_csv(acc_motion_waist_path)
acc_suffix = os.path.basename(acc_motion_waist_path).replace(".csv","").split("_")[-1]
acc_motion_waist.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_waist.columns
]

# --- Gyroscope forearm ---
gyro_motion_forearm_path = os.path.join(DATA_PATH, "Gyroscope_walking_forearm.csv")
gyro_motion_forearm = pd.read_csv(gyro_motion_forearm_path)
gyro_suffix = os.path.basename(gyro_motion_forearm_path).replace(".csv","").split("_")[-1]
gyro_motion_forearm.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_forearm.columns
]

# --- Accelerometer forearm ---
acc_motion_forearm_path = os.path.join(DATA_PATH, "acc_walking_forearm.csv")
acc_motion_forearm = pd.read_csv(acc_motion_forearm_path)
acc_suffix = os.path.basename(acc_motion_forearm_path).replace(".csv","").split("_")[-1]
acc_motion_forearm.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_forearm.columns
]

# --- Gyroscope head ---
gyro_motion_head_path = os.path.join(DATA_PATH, "Gyroscope_walking_head.csv")
gyro_motion_head = pd.read_csv(gyro_motion_head_path)
gyro_suffix = os.path.basename(gyro_motion_head_path).replace(".csv","").split("_")[-1]
gyro_motion_head.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_head.columns
]

# --- Accelerometer head ---
acc_motion_head_path = os.path.join(DATA_PATH, "acc_walking_head.csv")
acc_motion_head = pd.read_csv(acc_motion_head_path)
acc_suffix = os.path.basename(acc_motion_head_path).replace(".csv","").split("_")[-1]
acc_motion_head.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_head.columns
]

# --- Gyroscope chest ---
gyro_motion_chest_path = os.path.join(DATA_PATH, "Gyroscope_walking_chest.csv")
gyro_motion_chest = pd.read_csv(gyro_motion_chest_path)
gyro_suffix = os.path.basename(gyro_motion_chest_path).replace(".csv","").split("_")[-1]
gyro_motion_chest.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_chest.columns
]

# --- Accelerometer forearm ---
acc_motion_chest_path = os.path.join(DATA_PATH, "acc_walking_chest.csv")
acc_motion_chest = pd.read_csv(acc_motion_chest_path)
acc_suffix = os.path.basename(acc_motion_chest_path).replace(".csv","").split("_")[-1]
acc_motion_chest.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_chest.columns
]

# --- Gyroscope shin ---
gyro_motion_shin_path = os.path.join(DATA_PATH, "Gyroscope_walking_shin.csv")
gyro_motion_shin = pd.read_csv(gyro_motion_shin_path)
gyro_suffix = os.path.basename(gyro_motion_shin_path).replace(".csv","").split("_")[-1]
gyro_motion_shin.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_shin.columns
]

# --- Accelerometer shin ---
acc_motion_shin_path = os.path.join(DATA_PATH, "acc_walking_shin.csv")
acc_motion_shin = pd.read_csv(acc_motion_shin_path)
acc_suffix = os.path.basename(acc_motion_shin_path).replace(".csv","").split("_")[-1]
acc_motion_shin.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_shin.columns
]

# --- Gyroscope upperearm ---
gyro_motion_upperarm_path = os.path.join(DATA_PATH, "Gyroscope_walking_upperarm.csv")
gyro_motion_upperarm = pd.read_csv(gyro_motion_upperarm_path)
gyro_suffix = os.path.basename(gyro_motion_upperarm_path).replace(".csv","").split("_")[-1]
gyro_motion_upperarm.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_upperarm.columns
]

# --- Accelerometer upperarm ---
acc_motion_upperarm_path = os.path.join(DATA_PATH, "acc_walking_upperarm.csv")
acc_motion_upperarm = pd.read_csv(acc_motion_upperarm_path)
acc_suffix = os.path.basename(acc_motion_upperarm_path).replace(".csv","").split("_")[-1]
acc_motion_upperarm.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_upperarm.columns
]

# --- Combine ---
proband14 = pd.concat(
    [
        gyro_motion_waist, 
        acc_motion_waist, 
        gyro_motion_forearm, 
        acc_motion_forearm,
        gyro_motion_head,
        acc_motion_head,
        gyro_motion_chest,
        acc_motion_chest,
        gyro_motion_shin,
        acc_motion_shin,
        gyro_motion_upperarm,
        acc_motion_upperarm],
        axis=1)

# drop id/time
proband14 = proband14.loc[:, ~proband14.columns.str.contains("id|time", case=False, regex=True)]

# uppercase
proband14.columns = proband14.columns.str.upper()

# waist -> pelvis
proband14.columns = proband14.columns.str.replace("WAIST", "PELVIS", regex=False)
proband14.columns = proband14.columns.str.replace("CHEST", "TRUNK", regex=False)
proband14.columns = proband14.columns.str.replace("SHIN", "SHANK", regex=False)

# drop id/time again (not necessary, but harmless)
proband14 = proband14.loc[:, ~proband14.columns.str.contains("id|time", case=False, regex=True)]

proband14

,PELVIS_GYR_X,PELVIS_GYR_Y,PELVIS_GYR_Z,PELVIS_ACC_X,PELVIS_ACC_Y,PELVIS_ACC_Z,L_FOREARM_GYR_X,L_FOREARM_GYR_Y,L_FOREARM_GYR_Z,L_FOREARM_ACC_X,...,L_SHANK_GYR_Z,L_SHANK_ACC_X,L_SHANK_ACC_Y,L_SHANK_ACC_Z,L_UPPERARM_GYR_X,L_UPPERARM_GYR_Y,L_UPPERARM_GYR_Z,L_UPPERARM_ACC_X,L_UPPERARM_ACC_Y,L_UPPERARM_ACC_Z
0,0.063915,-0.050569,0.123514,9.765948,-0.834379,1.520917,0.019440,0.002701,-0.024658,-8.73846,...,-0.036346,1.461660,10.054450,-0.078410,-0.025962,-0.002749,-0.002138,0.037110,10.083180,1.662175
1,0.057501,-0.053012,0.121071,9.859921,-0.903213,1.561020,0.011963,0.008041,-0.024658,-8.71764,...,-0.040012,1.360505,10.035895,-0.122703,-0.018937,-0.006720,-0.002443,0.014964,10.090961,1.637634
2,0.048338,-0.064619,0.118627,9.850345,-0.930746,1.546654,0.009827,0.004837,-0.017181,-8.69508,...,-0.035736,1.367688,10.039486,-0.117914,-0.032070,-0.003665,0.005192,-0.084396,10.110115,1.607108
3,0.047422,-0.054540,0.122598,9.818023,-0.860715,1.583166,0.009827,0.002701,-0.005432,-8.70235,...,-0.033598,1.389834,10.012551,-0.121506,-0.027794,0.002749,0.010079,-0.134674,10.127473,1.504157
4,0.048338,-0.049653,0.127790,9.706693,-0.871489,1.601122,0.004486,-0.002640,-0.006500,-8.74609,...,-0.036652,1.464054,10.035296,-0.153827,-0.028100,0.000000,-0.001527,-0.075417,10.072407,1.541267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [101]:
import os, json
import pandas as pd
DATA_PATH_csv=os.path.join(
    BOX_ROOT,
    "WHT Datasets",
    "01_columns_synced",
    "RealWorldHAR",
    "PROBAND 14")

output_path = os.path.join(DATA_PATH_csv, "walking.csv")
proband14.to_csv(output_path, index=False)

print("Saved to:", output_path)

Saved to: /Users/aprillin/Library/CloudStorage/Box-Box/WHT Datasets/01_columns_synced/RealWorldHAR/PROBAND 14/walking.csv

In [102]:
# --- Gyroscope waist ---
gyro_motion_waist_path = os.path.join(DATA_PATH, "Gyroscope_running_waist.csv")
gyro_motion_waist = pd.read_csv(gyro_motion_waist_path)
gyro_suffix = os.path.basename(gyro_motion_waist_path).replace(".csv","").split("_")[-1]
gyro_motion_waist.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_waist.columns
]

# --- Accelerometer waist ---
acc_motion_waist_path = os.path.join(DATA_PATH, "acc_running_waist.csv")
acc_motion_waist = pd.read_csv(acc_motion_waist_path)
acc_suffix = os.path.basename(acc_motion_waist_path).replace(".csv","").split("_")[-1]
acc_motion_waist.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_waist.columns
]

# --- Gyroscope forearm ---
gyro_motion_forearm_path = os.path.join(DATA_PATH, "Gyroscope_running_forearm.csv")
gyro_motion_forearm = pd.read_csv(gyro_motion_forearm_path)
gyro_suffix = os.path.basename(gyro_motion_forearm_path).replace(".csv","").split("_")[-1]
gyro_motion_forearm.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_forearm.columns
]

# --- Accelerometer forearm ---
acc_motion_forearm_path = os.path.join(DATA_PATH, "acc_running_forearm.csv")
acc_motion_forearm = pd.read_csv(acc_motion_forearm_path)
acc_suffix = os.path.basename(acc_motion_forearm_path).replace(".csv","").split("_")[-1]
acc_motion_forearm.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_forearm.columns
]

# --- Gyroscope head ---
gyro_motion_head_path = os.path.join(DATA_PATH, "Gyroscope_running_head.csv")
gyro_motion_head = pd.read_csv(gyro_motion_head_path)
gyro_suffix = os.path.basename(gyro_motion_head_path).replace(".csv","").split("_")[-1]
gyro_motion_head.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_head.columns
]

# --- Accelerometer head ---
acc_motion_head_path = os.path.join(DATA_PATH, "acc_running_head.csv")
acc_motion_head = pd.read_csv(acc_motion_head_path)
acc_suffix = os.path.basename(acc_motion_head_path).replace(".csv","").split("_")[-1]
acc_motion_head.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_head.columns
]

# --- Gyroscope chest ---
gyro_motion_chest_path = os.path.join(DATA_PATH, "Gyroscope_running_chest.csv")
gyro_motion_chest = pd.read_csv(gyro_motion_chest_path)
gyro_suffix = os.path.basename(gyro_motion_chest_path).replace(".csv","").split("_")[-1]
gyro_motion_chest.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_chest.columns
]

# --- Accelerometer forearm ---
acc_motion_chest_path = os.path.join(DATA_PATH, "acc_running_chest.csv")
acc_motion_chest = pd.read_csv(acc_motion_chest_path)
acc_suffix = os.path.basename(acc_motion_chest_path).replace(".csv","").split("_")[-1]
acc_motion_chest.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_chest.columns
]

# --- Gyroscope shin ---
gyro_motion_shin_path = os.path.join(DATA_PATH, "Gyroscope_running_shin.csv")
gyro_motion_shin = pd.read_csv(gyro_motion_shin_path)
gyro_suffix = os.path.basename(gyro_motion_shin_path).replace(".csv","").split("_")[-1]
gyro_motion_shin.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_shin.columns
]

# --- Accelerometer shin ---
acc_motion_shin_path = os.path.join(DATA_PATH, "acc_running_shin.csv")
acc_motion_shin = pd.read_csv(acc_motion_shin_path)
acc_suffix = os.path.basename(acc_motion_shin_path).replace(".csv","").split("_")[-1]
acc_motion_shin.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_shin.columns
]

# --- Gyroscope upperearm ---
gyro_motion_upperarm_path = os.path.join(DATA_PATH, "Gyroscope_running_upperarm.csv")
gyro_motion_upperarm = pd.read_csv(gyro_motion_upperarm_path)
gyro_suffix = os.path.basename(gyro_motion_upperarm_path).replace(".csv","").split("_")[-1]
gyro_motion_upperarm.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_upperarm.columns
]

# --- Accelerometer upperarm ---
acc_motion_upperarm_path = os.path.join(DATA_PATH, "acc_running_upperarm.csv")
acc_motion_upperarm = pd.read_csv(acc_motion_upperarm_path)
acc_suffix = os.path.basename(acc_motion_upperarm_path).replace(".csv","").split("_")[-1]
acc_motion_upperarm.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_upperarm.columns
]

# --- Combine ---
proband14 = pd.concat(
    [
        gyro_motion_waist, 
        acc_motion_waist, 
        gyro_motion_forearm, 
        acc_motion_forearm,
        gyro_motion_head,
        acc_motion_head,
        gyro_motion_chest,
        acc_motion_chest,
        gyro_motion_shin,
        acc_motion_shin,
        gyro_motion_upperarm,
        acc_motion_upperarm],
        axis=1)

# drop id/time
proband14 = proband14.loc[:, ~proband14.columns.str.contains("id|time", case=False, regex=True)]

# uppercase
proband14.columns = proband14.columns.str.upper()

# waist -> pelvis
proband14.columns = proband14.columns.str.replace("WAIST", "PELVIS", regex=False)
proband14.columns = proband14.columns.str.replace("CHEST", "TRUNK", regex=False)
proband14.columns = proband14.columns.str.replace("SHIN", "SHANK", regex=False)

# drop id/time again (not necessary, but harmless)
proband14 = proband14.loc[:, ~proband14.columns.str.contains("id|time", case=False, regex=True)]

proband14

,PELVIS_GYR_X,PELVIS_GYR_Y,PELVIS_GYR_Z,PELVIS_ACC_X,PELVIS_ACC_Y,PELVIS_ACC_Z,L_FOREARM_GYR_X,L_FOREARM_GYR_Y,L_FOREARM_GYR_Z,L_FOREARM_ACC_X,...,L_SHANK_GYR_Z,L_SHANK_ACC_X,L_SHANK_ACC_Y,L_SHANK_ACC_Z,L_UPPERARM_GYR_X,L_UPPERARM_GYR_Y,L_UPPERARM_GYR_Z,L_UPPERARM_ACC_X,L_UPPERARM_ACC_Y,L_UPPERARM_ACC_Z
0,-0.033850,-0.051432,-0.022961,10.061034,0.122104,1.101931,0.255707,0.188660,0.509674,-8.63521,...,-0.031154,2.381034,9.902418,-0.589572,0.009774,0.082161,0.020464,-2.478597,9.703101,-0.168193
1,-0.037515,-0.081670,-0.019601,10.126875,0.022745,1.068412,0.272797,0.161957,0.484039,-8.74303,...,-0.038179,2.333748,9.883863,-0.554258,0.012828,0.114843,0.017715,-2.612673,9.804256,-0.252588
2,-0.029268,-0.085641,-0.027542,10.071808,-0.031723,0.893636,0.305908,0.117096,0.454132,-8.79810,...,-0.038790,2.280477,9.909601,-0.533907,0.010385,0.108429,0.026573,-2.679112,9.845556,-0.261567
3,-0.013386,-0.066704,-0.023571,9.934141,0.041899,0.851139,0.294159,0.088257,0.419952,-8.85831,...,-0.034514,2.275090,9.891644,-0.693121,0.008858,0.074220,0.050091,-2.603694,9.852140,-0.190938
4,-0.004223,-0.030663,-0.016241,9.842564,0.183755,0.935534,0.219391,0.051941,0.361206,-8.95056,...,-0.039401,2.351106,9.845556,-0.654814,0.009468,0.043066,0.058948,-2.516905,9.814431,-0.115520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31414,NaN,NaN,NaN,NaN,NaN,NaN,0.309113,-0.029236,-0.133331,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31415,NaN,NaN,NaN,NaN,NaN,NaN,0.273865,-0.083710,-0.200623,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31416,NaN,NaN,NaN,NaN,NaN,NaN,0.237549,-0.125366,-0.240143,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31417,NaN,NaN,NaN,NaN,NaN,NaN,0.164917,-0.124298,-0.272186,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31418,NaN,NaN,NaN,NaN,NaN,NaN,0.023926,-0.147797,-0.315979,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
output_path = os.path.join(DATA_PATH_csv, "running.csv")
proband14.to_csv(output_path, index=False)

print("Saved to:", output_path)

Saved to: /Users/aprillin/Library/CloudStorage/Box-Box/WHT Datasets/01_columns_synced/RealWorldHAR/PROBAND 14/running.csv

In [104]:
BOX_ROOT = os.path.expanduser("~/Library/CloudStorage/Box-Box")
DATA_PATH=os.path.join(
    BOX_ROOT,
    "WHT Datasets",
    "00_raw",
    "RealWorldHAR",
    "realworld2016_dataset",
    "proband13",
    "data")
# --- Gyroscope waist ---
gyro_motion_waist_path = os.path.join(DATA_PATH, "Gyroscope_standing_waist.csv")
gyro_motion_waist = pd.read_csv(gyro_motion_waist_path)
gyro_suffix = os.path.basename(gyro_motion_waist_path).replace(".csv","").split("_")[-1]
gyro_motion_waist.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_waist.columns
]

# --- Accelerometer waist ---
acc_motion_waist_path = os.path.join(DATA_PATH, "acc_standing_waist.csv")
acc_motion_waist = pd.read_csv(acc_motion_waist_path)
acc_suffix = os.path.basename(acc_motion_waist_path).replace(".csv","").split("_")[-1]
acc_motion_waist.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_waist.columns
]

# --- Gyroscope forearm ---
gyro_motion_forearm_path = os.path.join(DATA_PATH, "Gyroscope_standing_forearm.csv")
gyro_motion_forearm = pd.read_csv(gyro_motion_forearm_path)
gyro_suffix = os.path.basename(gyro_motion_forearm_path).replace(".csv","").split("_")[-1]
gyro_motion_forearm.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_forearm.columns
]

# --- Accelerometer forearm ---
acc_motion_forearm_path = os.path.join(DATA_PATH, "acc_standing_forearm.csv")
acc_motion_forearm = pd.read_csv(acc_motion_forearm_path)
acc_suffix = os.path.basename(acc_motion_forearm_path).replace(".csv","").split("_")[-1]
acc_motion_forearm.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_forearm.columns
]

# --- Gyroscope head ---
gyro_motion_head_path = os.path.join(DATA_PATH, "Gyroscope_standing_head.csv")
gyro_motion_head = pd.read_csv(gyro_motion_head_path)
gyro_suffix = os.path.basename(gyro_motion_head_path).replace(".csv","").split("_")[-1]
gyro_motion_head.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_head.columns
]

# --- Accelerometer head ---
acc_motion_head_path = os.path.join(DATA_PATH, "acc_standing_head.csv")
acc_motion_head = pd.read_csv(acc_motion_head_path)
acc_suffix = os.path.basename(acc_motion_head_path).replace(".csv","").split("_")[-1]
acc_motion_head.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_head.columns
]

# --- Gyroscope chest ---
gyro_motion_chest_path = os.path.join(DATA_PATH, "Gyroscope_standing_chest.csv")
gyro_motion_chest = pd.read_csv(gyro_motion_chest_path)
gyro_suffix = os.path.basename(gyro_motion_chest_path).replace(".csv","").split("_")[-1]
gyro_motion_chest.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_chest.columns
]

# --- Accelerometer forearm ---
acc_motion_chest_path = os.path.join(DATA_PATH, "acc_standing_chest.csv")
acc_motion_chest = pd.read_csv(acc_motion_chest_path)
acc_suffix = os.path.basename(acc_motion_chest_path).replace(".csv","").split("_")[-1]
acc_motion_chest.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_chest.columns
]

# --- Gyroscope shin ---
gyro_motion_shin_path = os.path.join(DATA_PATH, "Gyroscope_standing_shin.csv")
gyro_motion_shin = pd.read_csv(gyro_motion_shin_path)
gyro_suffix = os.path.basename(gyro_motion_shin_path).replace(".csv","").split("_")[-1]
gyro_motion_shin.columns  = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_shin.columns
]

# --- Accelerometer shin ---
acc_motion_shin_path = os.path.join(DATA_PATH, "acc_standing_shin.csv")
acc_motion_shin = pd.read_csv(acc_motion_shin_path)
acc_suffix = os.path.basename(acc_motion_shin_path).replace(".csv","").split("_")[-1]
acc_motion_shin.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_shin.columns
]

# --- Gyroscope upperearm ---
gyro_motion_upperarm_path = os.path.join(DATA_PATH, "Gyroscope_standing_upperarm.csv")
gyro_motion_upperarm = pd.read_csv(gyro_motion_upperarm_path)
gyro_suffix = os.path.basename(gyro_motion_upperarm_path).replace(".csv","").split("_")[-1]
gyro_motion_upperarm.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_upperarm.columns
]

# --- Accelerometer upperarm ---
acc_motion_upperarm_path = os.path.join(DATA_PATH, "acc_standing_upperarm.csv")
acc_motion_upperarm = pd.read_csv(acc_motion_upperarm_path)
acc_suffix = os.path.basename(acc_motion_upperarm_path).replace(".csv","").split("_")[-1]
acc_motion_upperarm.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_upperarm.columns
]

# --- Combine ---
proband13 = pd.concat(
    [
        gyro_motion_waist, 
        acc_motion_waist, 
        gyro_motion_forearm, 
        acc_motion_forearm,
        gyro_motion_head,
        acc_motion_head,
        gyro_motion_chest,
        acc_motion_chest,
        gyro_motion_shin,
        acc_motion_shin,
        gyro_motion_upperarm,
        acc_motion_upperarm],
        axis=1)

# drop id/time
proband13 = proband13.loc[:, ~proband13.columns.str.contains("id|time", case=False, regex=True)]

# uppercase
proband13.columns = proband13.columns.str.upper()

# waist -> pelvis
proband13.columns = proband13.columns.str.replace("WAIST", "PELVIS", regex=False)
proband13.columns = proband13.columns.str.replace("CHEST", "TRUNK", regex=False)
proband13.columns = proband13.columns.str.replace("SHIN", "SHANK", regex=False)

# drop id/time again (not necessary, but harmless)
proband13 = proband13.loc[:, ~proband13.columns.str.contains("id|time", case=False, regex=True)]

proband13

import os, json
import pandas as pd
DATA_PATH_csv=os.path.join(
    BOX_ROOT,
    "WHT Datasets",
    "01_columns_synced",
    "RealWorldHAR",
    "PROBAND 13")

output_path = os.path.join(DATA_PATH_csv, "standing.csv")
proband13.to_csv(output_path, index=False)

print("Saved to:", output_path)

Saved to: /Users/aprillin/Library/CloudStorage/Box-Box/WHT Datasets/01_columns_synced/RealWorldHAR/PROBAND 13/standing.csv

In [105]:

# --- Gyroscope waist ---
gyro_motion_waist_path = os.path.join(DATA_PATH, "Gyroscope_sitting_waist.csv")
gyro_motion_waist = pd.read_csv(gyro_motion_waist_path)
gyro_suffix = os.path.basename(gyro_motion_waist_path).replace(".csv","").split("_")[-1]
gyro_motion_waist.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_waist.columns
]

# --- Accelerometer waist ---
acc_motion_waist_path = os.path.join(DATA_PATH, "acc_sitting_waist.csv")
acc_motion_waist = pd.read_csv(acc_motion_waist_path)
acc_suffix = os.path.basename(acc_motion_waist_path).replace(".csv","").split("_")[-1]
acc_motion_waist.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_waist.columns
]

# --- Gyroscope forearm ---
gyro_motion_forearm_path = os.path.join(DATA_PATH, "Gyroscope_sitting_forearm.csv")
gyro_motion_forearm = pd.read_csv(gyro_motion_forearm_path)
gyro_suffix = os.path.basename(gyro_motion_forearm_path).replace(".csv","").split("_")[-1]
gyro_motion_forearm.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_forearm.columns
]

# --- Accelerometer forearm ---
acc_motion_forearm_path = os.path.join(DATA_PATH, "acc_sitting_forearm.csv")
acc_motion_forearm = pd.read_csv(acc_motion_forearm_path)
acc_suffix = os.path.basename(acc_motion_forearm_path).replace(".csv","").split("_")[-1]
acc_motion_forearm.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_forearm.columns
]

# --- Gyroscope head ---
gyro_motion_head_path = os.path.join(DATA_PATH, "Gyroscope_sitting_head.csv")
gyro_motion_head = pd.read_csv(gyro_motion_head_path)
gyro_suffix = os.path.basename(gyro_motion_head_path).replace(".csv","").split("_")[-1]
gyro_motion_head.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_head.columns
]

# --- Accelerometer head ---
acc_motion_head_path = os.path.join(DATA_PATH, "acc_sitting_head.csv")
acc_motion_head = pd.read_csv(acc_motion_head_path)
acc_suffix = os.path.basename(acc_motion_head_path).replace(".csv","").split("_")[-1]
acc_motion_head.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_head.columns
]

# --- Gyroscope chest ---
gyro_motion_chest_path = os.path.join(DATA_PATH, "Gyroscope_sitting_chest.csv")
gyro_motion_chest = pd.read_csv(gyro_motion_chest_path)
gyro_suffix = os.path.basename(gyro_motion_chest_path).replace(".csv","").split("_")[-1]
gyro_motion_chest.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_chest.columns
]

# --- Accelerometer forearm ---
acc_motion_chest_path = os.path.join(DATA_PATH, "acc_sitting_chest.csv")
acc_motion_chest = pd.read_csv(acc_motion_chest_path)
acc_suffix = os.path.basename(acc_motion_chest_path).replace(".csv","").split("_")[-1]
acc_motion_chest.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_chest.columns
]

# --- Gyroscope shin ---
gyro_motion_shin_path = os.path.join(DATA_PATH, "Gyroscope_sitting_shin.csv")
gyro_motion_shin = pd.read_csv(gyro_motion_shin_path)
gyro_suffix = os.path.basename(gyro_motion_shin_path).replace(".csv","").split("_")[-1]
gyro_motion_shin.columns  = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_shin.columns
]

# --- Accelerometer shin ---
acc_motion_shin_path = os.path.join(DATA_PATH, "acc_sitting_shin.csv")
acc_motion_shin = pd.read_csv(acc_motion_shin_path)
acc_suffix = os.path.basename(acc_motion_shin_path).replace(".csv","").split("_")[-1]
acc_motion_shin.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_shin.columns
]

# --- Gyroscope upperearm ---
gyro_motion_upperarm_path = os.path.join(DATA_PATH, "Gyroscope_sitting_upperarm.csv")
gyro_motion_upperarm = pd.read_csv(gyro_motion_upperarm_path)
gyro_suffix = os.path.basename(gyro_motion_upperarm_path).replace(".csv","").split("_")[-1]
gyro_motion_upperarm.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_upperarm.columns
]

# --- Accelerometer upperarm ---
acc_motion_upperarm_path = os.path.join(DATA_PATH, "acc_sitting_upperarm.csv")
acc_motion_upperarm = pd.read_csv(acc_motion_upperarm_path)
acc_suffix = os.path.basename(acc_motion_upperarm_path).replace(".csv","").split("_")[-1]
acc_motion_upperarm.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_upperarm.columns
]

# --- Combine ---
proband14 = pd.concat(
    [
        gyro_motion_waist, 
        acc_motion_waist, 
        gyro_motion_forearm, 
        acc_motion_forearm,
        gyro_motion_head,
        acc_motion_head,
        gyro_motion_chest,
        acc_motion_chest,
        gyro_motion_shin,
        acc_motion_shin,
        gyro_motion_upperarm,
        acc_motion_upperarm],
        axis=1)

# drop id/time
proband14 = proband14.loc[:, ~proband14.columns.str.contains("id|time", case=False, regex=True)]

# uppercase
proband14.columns = proband14.columns.str.upper()

# waist -> pelvis
proband14.columns = proband14.columns.str.replace("WAIST", "PELVIS", regex=False)
proband14.columns = proband14.columns.str.replace("CHEST", "TRUNK", regex=False)
proband14.columns = proband14.columns.str.replace("SHIN", "SHANK", regex=False)

# drop id/time again (not necessary, but harmless)
proband14 = proband14.loc[:, ~proband14.columns.str.contains("id|time", case=False, regex=True)]

proband14

import os, json
import pandas as pd
DATA_PATH_csv=os.path.join(
    BOX_ROOT,
    "WHT Datasets",
    "01_columns_synced",
    "RealWorldHAR",
    "PROBAND 14")

output_path = os.path.join(DATA_PATH_csv, "sitting.csv")
proband14.to_csv(output_path, index=False)

print("Saved to:", output_path)
proband14.to_csv(output_path, index=False)

print("Saved to:", output_path)

Saved to: /Users/aprillin/Library/CloudStorage/Box-Box/WHT Datasets/01_columns_synced/RealWorldHAR/PROBAND 14/sitting.csv
Saved to: /Users/aprillin/Library/CloudStorage/Box-Box/WHT Datasets/01_columns_synced/RealWorldHAR/PROBAND 14/sitting.csv

In [106]:

# --- Gyroscope waist ---
gyro_motion_waist_path = os.path.join(DATA_PATH, "Gyroscope_lying_waist.csv")
gyro_motion_waist = pd.read_csv(gyro_motion_waist_path)
gyro_suffix = os.path.basename(gyro_motion_waist_path).replace(".csv","").split("_")[-1]
gyro_motion_waist.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_waist.columns
]

# --- Accelerometer waist ---
acc_motion_waist_path = os.path.join(DATA_PATH, "acc_lying_waist.csv")
acc_motion_waist = pd.read_csv(acc_motion_waist_path)
acc_suffix = os.path.basename(acc_motion_waist_path).replace(".csv","").split("_")[-1]
acc_motion_waist.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_waist.columns
]

# --- Gyroscope forearm ---
gyro_motion_forearm_path = os.path.join(DATA_PATH, "Gyroscope_lying_forearm.csv")
gyro_motion_forearm = pd.read_csv(gyro_motion_forearm_path)
gyro_suffix = os.path.basename(gyro_motion_forearm_path).replace(".csv","").split("_")[-1]
gyro_motion_forearm.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_forearm.columns
]

# --- Accelerometer forearm ---
acc_motion_forearm_path = os.path.join(DATA_PATH, "acc_lying_forearm.csv")
acc_motion_forearm = pd.read_csv(acc_motion_forearm_path)
acc_suffix = os.path.basename(acc_motion_forearm_path).replace(".csv","").split("_")[-1]
acc_motion_forearm.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_forearm.columns
]

# --- Gyroscope head ---
gyro_motion_head_path = os.path.join(DATA_PATH, "Gyroscope_lying_head.csv")
gyro_motion_head = pd.read_csv(gyro_motion_head_path)
gyro_suffix = os.path.basename(gyro_motion_head_path).replace(".csv","").split("_")[-1]
gyro_motion_head.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_head.columns
]

# --- Accelerometer head ---
acc_motion_head_path = os.path.join(DATA_PATH, "acc_lying_head.csv")
acc_motion_head = pd.read_csv(acc_motion_head_path)
acc_suffix = os.path.basename(acc_motion_head_path).replace(".csv","").split("_")[-1]
acc_motion_head.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_head.columns
]

# --- Gyroscope chest ---
gyro_motion_chest_path = os.path.join(DATA_PATH, "Gyroscope_lying_chest.csv")
gyro_motion_chest = pd.read_csv(gyro_motion_chest_path)
gyro_suffix = os.path.basename(gyro_motion_chest_path).replace(".csv","").split("_")[-1]
gyro_motion_chest.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_chest.columns
]

# --- Accelerometer forearm ---
acc_motion_chest_path = os.path.join(DATA_PATH, "acc_lying_chest.csv")
acc_motion_chest = pd.read_csv(acc_motion_chest_path)
acc_suffix = os.path.basename(acc_motion_chest_path).replace(".csv","").split("_")[-1]
acc_motion_chest.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_chest.columns
]

# --- Gyroscope shin ---
gyro_motion_shin_path = os.path.join(DATA_PATH, "Gyroscope_lying_shin.csv")
gyro_motion_shin = pd.read_csv(gyro_motion_shin_path)
gyro_suffix = os.path.basename(gyro_motion_shin_path).replace(".csv","").split("_")[-1]
gyro_motion_shin.columns  = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_shin.columns
]

# --- Accelerometer shin ---
acc_motion_shin_path = os.path.join(DATA_PATH, "acc_lying_shin.csv")
acc_motion_shin = pd.read_csv(acc_motion_shin_path)
acc_suffix = os.path.basename(acc_motion_shin_path).replace(".csv","").split("_")[-1]
acc_motion_shin.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_shin.columns
]

# --- Gyroscope upperearm ---
gyro_motion_upperarm_path = os.path.join(DATA_PATH, "Gyroscope_lying_upperarm.csv")
gyro_motion_upperarm = pd.read_csv(gyro_motion_upperarm_path)
gyro_suffix = os.path.basename(gyro_motion_upperarm_path).replace(".csv","").split("_")[-1]
gyro_motion_upperarm.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_upperarm.columns
]

# --- Accelerometer upperarm ---
acc_motion_upperarm_path = os.path.join(DATA_PATH, "acc_lying_upperarm.csv")
acc_motion_upperarm = pd.read_csv(acc_motion_upperarm_path)
acc_suffix = os.path.basename(acc_motion_upperarm_path).replace(".csv","").split("_")[-1]
acc_motion_upperarm.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_upperarm.columns
]

# --- Combine ---
proband14 = pd.concat(
    [
        gyro_motion_waist, 
        acc_motion_waist, 
        gyro_motion_forearm, 
        acc_motion_forearm,
        gyro_motion_head,
        acc_motion_head,
        gyro_motion_chest,
        acc_motion_chest,
        gyro_motion_shin,
        acc_motion_shin,
        gyro_motion_upperarm,
        acc_motion_upperarm],
        axis=1)

# drop id/time
proband14 = proband14.loc[:, ~proband14.columns.str.contains("id|time", case=False, regex=True)]

# uppercase
proband14.columns = proband14.columns.str.upper()

# waist -> pelvis
proband14.columns = proband14.columns.str.replace("WAIST", "PELVIS", regex=False)
proband14.columns = proband14.columns.str.replace("CHEST", "TRUNK", regex=False)
proband14.columns = proband14.columns.str.replace("SHIN", "SHANK", regex=False)

# drop id/time again (not necessary, but harmless)
proband14 = proband14.loc[:, ~proband14.columns.str.contains("id|time", case=False, regex=True)]

proband14


output_path = os.path.join(DATA_PATH_csv, "lying.csv")
proband14.to_csv(output_path, index=False)

print("Saved to:", output_path)

Saved to: /Users/aprillin/Library/CloudStorage/Box-Box/WHT Datasets/01_columns_synced/RealWorldHAR/PROBAND 14/lying.csv

In [107]:

# --- Gyroscope waist ---
gyro_motion_waist_path = os.path.join(DATA_PATH, "Gyroscope_jumping_waist.csv")
gyro_motion_waist = pd.read_csv(gyro_motion_waist_path)
gyro_suffix = os.path.basename(gyro_motion_waist_path).replace(".csv","").split("_")[-1]
gyro_motion_waist.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_waist.columns
]

# --- Accelerometer waist ---
acc_motion_waist_path = os.path.join(DATA_PATH, "acc_jumping_waist.csv")
acc_motion_waist = pd.read_csv(acc_motion_waist_path)
acc_suffix = os.path.basename(acc_motion_waist_path).replace(".csv","").split("_")[-1]
acc_motion_waist.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_waist.columns
]

# --- Gyroscope forearm ---
gyro_motion_forearm_path = os.path.join(DATA_PATH, "Gyroscope_jumping_forearm.csv")
gyro_motion_forearm = pd.read_csv(gyro_motion_forearm_path)
gyro_suffix = os.path.basename(gyro_motion_forearm_path).replace(".csv","").split("_")[-1]
gyro_motion_forearm.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_forearm.columns
]

# --- Accelerometer forearm ---
acc_motion_forearm_path = os.path.join(DATA_PATH, "acc_jumping_forearm.csv")
acc_motion_forearm = pd.read_csv(acc_motion_forearm_path)
acc_suffix = os.path.basename(acc_motion_forearm_path).replace(".csv","").split("_")[-1]
acc_motion_forearm.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_forearm.columns
]

# --- Gyroscope head ---
gyro_motion_head_path = os.path.join(DATA_PATH, "Gyroscope_jumping_head.csv")
gyro_motion_head = pd.read_csv(gyro_motion_head_path)
gyro_suffix = os.path.basename(gyro_motion_head_path).replace(".csv","").split("_")[-1]
gyro_motion_head.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_head.columns
]

# --- Accelerometer head ---
acc_motion_head_path = os.path.join(DATA_PATH, "acc_jumping_head.csv")
acc_motion_head = pd.read_csv(acc_motion_head_path)
acc_suffix = os.path.basename(acc_motion_head_path).replace(".csv","").split("_")[-1]
acc_motion_head.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_head.columns
]

# --- Gyroscope chest ---
gyro_motion_chest_path = os.path.join(DATA_PATH, "Gyroscope_jumping_chest.csv")
gyro_motion_chest = pd.read_csv(gyro_motion_chest_path)
gyro_suffix = os.path.basename(gyro_motion_chest_path).replace(".csv","").split("_")[-1]
gyro_motion_chest.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_chest.columns
]

# --- Accelerometer forearm ---
acc_motion_chest_path = os.path.join(DATA_PATH, "acc_jumping_chest.csv")
acc_motion_chest = pd.read_csv(acc_motion_chest_path)
acc_suffix = os.path.basename(acc_motion_chest_path).replace(".csv","").split("_")[-1]
acc_motion_chest.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_chest.columns
]

# --- Gyroscope shin ---
gyro_motion_shin_path = os.path.join(DATA_PATH, "Gyroscope_jumping_shin.csv")
gyro_motion_shin = pd.read_csv(gyro_motion_shin_path)
gyro_suffix = os.path.basename(gyro_motion_shin_path).replace(".csv","").split("_")[-1]
gyro_motion_shin.columns  = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_shin.columns
]

# --- Accelerometer shin ---
acc_motion_shin_path = os.path.join(DATA_PATH, "acc_jumping_shin.csv")
acc_motion_shin = pd.read_csv(acc_motion_shin_path)
acc_suffix = os.path.basename(acc_motion_shin_path).replace(".csv","").split("_")[-1]
acc_motion_shin.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_shin.columns
]

# --- Gyroscope upperearm ---
gyro_motion_upperarm_path = os.path.join(DATA_PATH, "Gyroscope_jumping_upperarm.csv")
gyro_motion_upperarm = pd.read_csv(gyro_motion_upperarm_path)
gyro_suffix = os.path.basename(gyro_motion_upperarm_path).replace(".csv","").split("_")[-1]
gyro_motion_upperarm.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_upperarm.columns
]

# --- Accelerometer upperarm ---
acc_motion_upperarm_path = os.path.join(DATA_PATH, "acc_jumping_upperarm.csv")
acc_motion_upperarm = pd.read_csv(acc_motion_upperarm_path)
acc_suffix = os.path.basename(acc_motion_upperarm_path).replace(".csv","").split("_")[-1]
acc_motion_upperarm.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_upperarm.columns
]

# --- Combine ---
proband14 = pd.concat(
    [
        gyro_motion_waist, 
        acc_motion_waist, 
        gyro_motion_forearm, 
        acc_motion_forearm,
        gyro_motion_head,
        acc_motion_head,
        gyro_motion_chest,
        acc_motion_chest,
        gyro_motion_shin,
        acc_motion_shin,
        gyro_motion_upperarm,
        acc_motion_upperarm],
        axis=1)

# drop id/time
proband14 = proband14.loc[:, ~proband14.columns.str.contains("id|time", case=False, regex=True)]

# uppercase
proband14.columns = proband14.columns.str.upper()

# waist -> pelvis
proband14.columns = proband14.columns.str.replace("WAIST", "PELVIS", regex=False)
proband14.columns = proband14.columns.str.replace("CHEST", "TRUNK", regex=False)
proband14.columns = proband14.columns.str.replace("SHIN", "SHANK", regex=False)

# drop id/time again (not necessary, but harmless)
proband14 = proband14.loc[:, ~proband14.columns.str.contains("id|time", case=False, regex=True)]

proband14


output_path = os.path.join(DATA_PATH_csv, "jumping.csv")
proband14.to_csv(output_path, index=False)

print("Saved to:", output_path)

Saved to: /Users/aprillin/Library/CloudStorage/Box-Box/WHT Datasets/01_columns_synced/RealWorldHAR/PROBAND 14/jumping.csv

In [108]:

# --- Gyroscope waist ---
gyro_motion_waist_path = os.path.join(DATA_PATH, "Gyroscope_climbingup_waist.csv")
gyro_motion_waist = pd.read_csv(gyro_motion_waist_path)
gyro_suffix = os.path.basename(gyro_motion_waist_path).replace(".csv","").split("_")[-1]
gyro_motion_waist.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_waist.columns
]

# --- Accelerometer waist ---
acc_motion_waist_path = os.path.join(DATA_PATH, "acc_climbingup_waist.csv")
acc_motion_waist = pd.read_csv(acc_motion_waist_path)
acc_suffix = os.path.basename(acc_motion_waist_path).replace(".csv","").split("_")[-1]
acc_motion_waist.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_waist.columns
]

# --- Gyroscope forearm ---
gyro_motion_forearm_path = os.path.join(DATA_PATH, "Gyroscope_climbingup_forearm.csv")
gyro_motion_forearm = pd.read_csv(gyro_motion_forearm_path)
gyro_suffix = os.path.basename(gyro_motion_forearm_path).replace(".csv","").split("_")[-1]
gyro_motion_forearm.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_forearm.columns
]

# --- Accelerometer forearm ---
acc_motion_forearm_path = os.path.join(DATA_PATH, "acc_climbingup_forearm.csv")
acc_motion_forearm = pd.read_csv(acc_motion_forearm_path)
acc_suffix = os.path.basename(acc_motion_forearm_path).replace(".csv","").split("_")[-1]
acc_motion_forearm.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_forearm.columns
]

# --- Gyroscope head ---
gyro_motion_head_path = os.path.join(DATA_PATH, "Gyroscope_climbingup_head.csv")
gyro_motion_head = pd.read_csv(gyro_motion_head_path)
gyro_suffix = os.path.basename(gyro_motion_head_path).replace(".csv","").split("_")[-1]
gyro_motion_head.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_head.columns
]

# --- Accelerometer head ---
acc_motion_head_path = os.path.join(DATA_PATH, "acc_climbingup_head.csv")
acc_motion_head = pd.read_csv(acc_motion_head_path)
acc_suffix = os.path.basename(acc_motion_head_path).replace(".csv","").split("_")[-1]
acc_motion_head.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_head.columns
]

# --- Gyroscope chest ---
gyro_motion_chest_path = os.path.join(DATA_PATH, "Gyroscope_climbingup_chest.csv")
gyro_motion_chest = pd.read_csv(gyro_motion_chest_path)
gyro_suffix = os.path.basename(gyro_motion_chest_path).replace(".csv","").split("_")[-1]
gyro_motion_chest.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_chest.columns
]

# --- Accelerometer forearm ---
acc_motion_chest_path = os.path.join(DATA_PATH, "acc_climbingup_chest.csv")
acc_motion_chest = pd.read_csv(acc_motion_chest_path)
acc_suffix = os.path.basename(acc_motion_chest_path).replace(".csv","").split("_")[-1]
acc_motion_chest.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_chest.columns
]

# --- Gyroscope shin ---
gyro_motion_shin_path = os.path.join(DATA_PATH, "Gyroscope_climbingup_shin.csv")
gyro_motion_shin = pd.read_csv(gyro_motion_shin_path)
gyro_suffix = os.path.basename(gyro_motion_shin_path).replace(".csv","").split("_")[-1]
gyro_motion_shin.columns  = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_shin.columns
]

# --- Accelerometer shin ---
acc_motion_shin_path = os.path.join(DATA_PATH, "acc_climbingup_shin.csv")
acc_motion_shin = pd.read_csv(acc_motion_shin_path)
acc_suffix = os.path.basename(acc_motion_shin_path).replace(".csv","").split("_")[-1]
acc_motion_shin.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_shin.columns
]

# --- Gyroscope upperearm ---
gyro_motion_upperarm_path = os.path.join(DATA_PATH, "Gyroscope_climbingup_upperarm.csv")
gyro_motion_upperarm = pd.read_csv(gyro_motion_upperarm_path)
gyro_suffix = os.path.basename(gyro_motion_upperarm_path).replace(".csv","").split("_")[-1]
gyro_motion_upperarm.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_upperarm.columns
]

# --- Accelerometer upperarm ---
acc_motion_upperarm_path = os.path.join(DATA_PATH, "acc_climbingup_upperarm.csv")
acc_motion_upperarm = pd.read_csv(acc_motion_upperarm_path)
acc_suffix = os.path.basename(acc_motion_upperarm_path).replace(".csv","").split("_")[-1]
acc_motion_upperarm.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_upperarm.columns
]

# --- Combine ---
proband14 = pd.concat(
    [
        gyro_motion_waist, 
        acc_motion_waist, 
        gyro_motion_forearm, 
        acc_motion_forearm,
        gyro_motion_head,
        acc_motion_head,
        gyro_motion_chest,
        acc_motion_chest,
        gyro_motion_shin,
        acc_motion_shin,
        gyro_motion_upperarm,
        acc_motion_upperarm],
        axis=1)

# drop id/time
proband14 = proband14.loc[:, ~proband14.columns.str.contains("id|time", case=False, regex=True)]

# uppercase
proband14.columns = proband14.columns.str.upper()

# waist -> pelvis
proband14.columns = proband14.columns.str.replace("WAIST", "PELVIS", regex=False)
proband14.columns = proband14.columns.str.replace("CHEST", "TRUNK", regex=False)
proband14.columns = proband14.columns.str.replace("SHIN", "SHANK", regex=False)

# drop id/time again (not necessary, but harmless)
proband14 = proband14.loc[:, ~proband14.columns.str.contains("id|time", case=False, regex=True)]

proband14


output_path = os.path.join(DATA_PATH_csv, "climbingup.csv")
proband14.to_csv(output_path, index=False)

print("Saved to:", output_path)

Saved to: /Users/aprillin/Library/CloudStorage/Box-Box/WHT Datasets/01_columns_synced/RealWorldHAR/PROBAND 14/climbingup.csv

In [109]:

# --- Gyroscope waist ---
gyro_motion_waist_path = os.path.join(DATA_PATH, "Gyroscope_climbingdown_waist.csv")
gyro_motion_waist = pd.read_csv(gyro_motion_waist_path)
gyro_suffix = os.path.basename(gyro_motion_waist_path).replace(".csv","").split("_")[-1]
gyro_motion_waist.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_waist.columns
]

# --- Accelerometer waist ---
acc_motion_waist_path = os.path.join(DATA_PATH, "acc_climbingdown_waist.csv")
acc_motion_waist = pd.read_csv(acc_motion_waist_path)
acc_suffix = os.path.basename(acc_motion_waist_path).replace(".csv","").split("_")[-1]
acc_motion_waist.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_waist.columns
]

# --- Gyroscope forearm ---
gyro_motion_forearm_path = os.path.join(DATA_PATH, "Gyroscope_climbingdown_forearm.csv")
gyro_motion_forearm = pd.read_csv(gyro_motion_forearm_path)
gyro_suffix = os.path.basename(gyro_motion_forearm_path).replace(".csv","").split("_")[-1]
gyro_motion_forearm.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_forearm.columns
]

# --- Accelerometer forearm ---
acc_motion_forearm_path = os.path.join(DATA_PATH, "acc_climbingdown_forearm.csv")
acc_motion_forearm = pd.read_csv(acc_motion_forearm_path)
acc_suffix = os.path.basename(acc_motion_forearm_path).replace(".csv","").split("_")[-1]
acc_motion_forearm.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_forearm.columns
]

# --- Gyroscope head ---
gyro_motion_head_path = os.path.join(DATA_PATH, "Gyroscope_climbingdown_head.csv")
gyro_motion_head = pd.read_csv(gyro_motion_head_path)
gyro_suffix = os.path.basename(gyro_motion_head_path).replace(".csv","").split("_")[-1]
gyro_motion_head.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_head.columns
]

# --- Accelerometer head ---
acc_motion_head_path = os.path.join(DATA_PATH, "acc_climbingdown_head.csv")
acc_motion_head = pd.read_csv(acc_motion_head_path)
acc_suffix = os.path.basename(acc_motion_head_path).replace(".csv","").split("_")[-1]
acc_motion_head.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_head.columns
]

# --- Gyroscope chest ---
gyro_motion_chest_path = os.path.join(DATA_PATH, "Gyroscope_climbingdown_chest.csv")
gyro_motion_chest = pd.read_csv(gyro_motion_chest_path)
gyro_suffix = os.path.basename(gyro_motion_chest_path).replace(".csv","").split("_")[-1]
gyro_motion_chest.columns = [
    f"{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_chest.columns
]

# --- Accelerometer forearm ---
acc_motion_chest_path = os.path.join(DATA_PATH, "acc_climbingdown_chest.csv")
acc_motion_chest = pd.read_csv(acc_motion_chest_path)
acc_suffix = os.path.basename(acc_motion_chest_path).replace(".csv","").split("_")[-1]
acc_motion_chest.columns = [
    f"{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_chest.columns
]

# --- Gyroscope shin ---
gyro_motion_shin_path = os.path.join(DATA_PATH, "Gyroscope_climbingdown_shin.csv")
gyro_motion_shin = pd.read_csv(gyro_motion_shin_path)
gyro_suffix = os.path.basename(gyro_motion_shin_path).replace(".csv","").split("_")[-1]
gyro_motion_shin.columns  = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_shin.columns
]

# --- Accelerometer shin ---
acc_motion_shin_path = os.path.join(DATA_PATH, "acc_climbingdown_shin.csv")
acc_motion_shin = pd.read_csv(acc_motion_shin_path)
acc_suffix = os.path.basename(acc_motion_shin_path).replace(".csv","").split("_")[-1]
acc_motion_shin.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_shin.columns
]

# --- Gyroscope upperarm ---
gyro_motion_upperarm_path = os.path.join(DATA_PATH, "Gyroscope_climbingdown_upperarm.csv")
gyro_motion_upperarm = pd.read_csv(gyro_motion_upperarm_path)
gyro_suffix = os.path.basename(gyro_motion_upperarm_path).replace(".csv","").split("_")[-1]
gyro_motion_upperarm.columns = [
    f"l_{gyro_suffix}_gyr_{c.replace('attr_', '')}"
    for c in gyro_motion_upperarm.columns
]

# --- Accelerometer upperarm ---
acc_motion_upperarm_path = os.path.join(DATA_PATH, "acc_climbingdown_upperarm.csv")
acc_motion_upperarm = pd.read_csv(acc_motion_upperarm_path)
acc_suffix = os.path.basename(acc_motion_upperarm_path).replace(".csv","").split("_")[-1]
acc_motion_upperarm.columns = [
    f"l_{acc_suffix}_acc_{c.replace('attr_', '')}"
    for c in acc_motion_upperarm.columns
]

# --- Combine ---
proband14 = pd.concat(
    [
        gyro_motion_waist, 
        acc_motion_waist, 
        gyro_motion_forearm, 
        acc_motion_forearm,
        gyro_motion_head,
        acc_motion_head,
        gyro_motion_chest,
        acc_motion_chest,
        gyro_motion_shin,
        acc_motion_shin,
        gyro_motion_upperarm,
        acc_motion_upperarm],
        axis=1)

# drop id/time
proband14 = proband14.loc[:, ~proband14.columns.str.contains("id|time", case=False, regex=True)]

# uppercase
proband14.columns = proband14.columns.str.upper()

# waist -> pelvis
proband14.columns = proband14.columns.str.replace("WAIST", "PELVIS", regex=False)
proband14.columns = proband14.columns.str.replace("CHEST", "TRUNK", regex=False)
proband14.columns = proband14.columns.str.replace("SHIN", "SHANK", regex=False)

# drop id/time again (not necessary, but harmless)
proband14 = proband14.loc[:, ~proband14.columns.str.contains("id|time", case=False, regex=True)]

proband14


output_path = os.path.join(DATA_PATH_csv, "climbingdown.csv")
proband14.to_csv(output_path, index=False)

print("Saved to:", output_path)

Saved to: /Users/aprillin/Library/CloudStorage/Box-Box/WHT Datasets/01_columns_synced/RealWorldHAR/PROBAND 14/climbingdown.csv